### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by matyasvane** [HibiscusMC/HMCLeaves#1]
Hi, after adding the plugin the server stops. When removed, the server starts up fine.

**Error:**

```
---- Minecraft Crash Report ----
// // DO NOT REPORT THIS TO PAPER! REPORT TO PURPUR INSTEAD!// I feel sad now :(

Time: 2022-11-21 05:07:25
Description: Exception in server tick loop

net.minecraft.world.level.chunk.MissingPaletteEntryException: Missing Palette entry for index 21448.
	at net.minecraft.world.level.chunk.GlobalPalette.valueFor(GlobalPalette.java:34)
	at com.destroystokyo.paper.antixray.ChunkPacketBlockControllerAntiXray.<init>(ChunkPacketBlockControllerAntiXray.java:128)
	at net.minecraft.world.level.Level.<init>(Level.java:423)
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:531)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:591)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116)
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Server info:**
Purpur 1.19.2

**Comment by Fisher2911** [comment]
Hi, can you try it on a paper server?

**Comment by matyasvane** [comment]
Yes, wait the minutes

**Comment by matyasvane** [comment]
I download latest version of Paper:

```
[05:31:46 ERROR]: Encountered an unexpected exception
net.minecraft.world.level.chunk.MissingPaletteEntryException: Missing Palette entry for index 21448.
	at net.minecraft.world.level.chunk.GlobalPalette.valueFor(GlobalPalette.java:34) ~[?:?]
	at com.destroystokyo.paper.antixray.ChunkPacketBlockControllerAntiXray.<init>(ChunkPacketBlockControllerAntiXray.java:128) ~[paper-1.19.2.jar:git-Paper-279]
	at net.minecraft.world.level.Level.<init>(Level.java:358) ~[?:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:528) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:586) ~[paper-1.19.2.jar:git-Paper-279]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-279]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-279]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-279]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-279]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Fisher2911** [comment]
It looks like it has something to do with anti x ray, can you try disabling that if it isn't? If it is let me know.

**Comment by matyasvane** [comment]
Yes, if i disable xray fuction in paper-world-defaults.yml, server dont crash.

```
anticheat:
  anti-xray:
    enabled: false
    engine-mode: 2
    hidden-blocks:
    - air
    - amethyst_block
    - coal_ore
    - diamond_ore
    - emerald_ore
    - gold_ore
    - iron_ore
    - lapis_ore
    - deepslate_coal_ore
    - deepslate_iron_ore
    - deepslate_iron_ore
    - deepslate_gold_ore
    - deepslate_lapis_ore
    - deepslate_copper_ore
    - deepslate_redstone_ore
    - deepslate_emerald_ore
    - deepslate_diamond_ore
    - mossy_cobblestone
    - redstone_ore
    lava-obscures: false
    max-block-height: 126
    replacement-blocks:
    - chest
    - andesite
    - deepslate
    - diorite
    - dirt
    - granite
    - gravel
    - oak_planks
    - stone
    update-radius: 2
    use-permission: true
  obfuscation:
    items:
      hide-durability: false
      hide-itemmeta: false
      hide-itemmeta-with-visual-effects: false
```

**Comment by Fisher2911** [comment]
Okay, thank you for reporting the issue! Would you also be able to try it on purpur again? And I will try to add support for anti x ray very soon.

**Comment by matyasvane** [comment]
It's strange, but the server starts shutting down by itself right after loading, but I don't see any error in the console. I probably need to configure the plugin first.

**Comment by Fisher2911** [comment]
Yep! Make sure to set enabled: true in the config.yml after you setup your default state.

**Comment by matyasvane** [comment]
by the way @Fisher2911 do you want all bugs post there, or one bug = one issue page on github?

**Comment by Fisher2911** [comment]
One bug per issue please, thank you!

**Comment by Fisher2911** [comment]
@matyasvane 
This is fixed in the latest update
